spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:moiza}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1111}
