spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:moiza}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1111}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  access-time: 3600000 # 1시간
  refresh-time: 2592000000 # 30일
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}